[package]
name = "music-organizer-core"
version = "0.1.0"
edition = "2024"

[dependencies]
musicbrainz_rs = "0.12.0"
bitcode = "0.6.9"
redb = "3.1.0"
symphonia = { version = "0.5.5", features = ["mp3", "flac", "wav", "aiff", "vorbis", "aac", "isomp4"] }
thiserror = "2.0.18"